#!/usr/bin/env python3
"""
contains a new function that inserts a new doc
in col based on kwargs
"""

def insert_school(mongo_collection, **kwargs):
    """returns the new _id"""
    resp_obj = mongo_collection.insertOne(kwargs)

    return resp_obj.

